name: Build & Release pipeline

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: semantic version
        id: tag
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          version_format: "${major}.${minor}.${patch}"
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore src/HelloWorld.csproj

      - name: Build
        run: dotnet build src/HelloWorld.csproj -c Release --no-restore

      - name: Test
        run: dotnet test tests/HelloWorld.Tests.csproj -c Release

      - name: Test coverage
        run: dotnet test tests/HelloWorld.Tests.csproj -c Release --collect:"XPlat Code Coverage"

      - name: Publish
        run: dotnet publish src/HelloWorld.csproj -c Release -o app --no-build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image 
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USER }}/hello-world:v${{ steps.tag.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USER }}/hello-world:v${{ steps.tag.outputs.version }}

