name: Build & Release pipeline

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: semantic version
        id: tag
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "BREAKING CHANGE:"
          minor_pattern: "feat:"
          patch_pattern: "fix:"
          version_format: "${major}.${minor}.${patch}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image 
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USER }}/hello-world:v${{ steps.version.outputs.version }} .

      - name: Push Docker image
        run: |
          docker push docker.io/${{ secrets.DOCKERHUB_USER }}/hello-world:v${{ steps.version.outputs.version }}

